### ISSUE TITLE
Pokemon Custom Spawning (Suggestion)

### ISSUE THREAD

**Issue by mcmiked** [runescapejon/PokeTextures#2] opened 2019-03-09 23:14 UTC
Is there a way to add in a setting to give the natural pokemon that spawn a chance to be a custom texture? Also so that the NPC trainers can use the custom textures as well on their pokemon?

**Comment by runescapejon** [comment] 2019-03-10 05:34
Yes i can able to do but can you explain more on npc part? basically more information the better i can able to do these new features your requesting

**Comment by mcmiked** [comment] 2019-03-10 07:53
In the NPC trainer editor, some pokemon have special forms beside shiny, like charizard (pic attached). If there was a way to add the custom forms there, or some other way to those trainers, that would be incredible!

________________________________

**Comment by runescapejon** [comment] 2019-03-10 08:47
I will look into this npc trainer having custom texture pokemon but although it should have been a pixelmon feature. I don't know if is or not.

**Comment by mcmiked** [comment] 2019-03-10 09:01
Awesome! Thank you very much!

-------- Original message --------

**Comment by runescapejon** [comment] 2019-03-14 04:29
Closing this because it's a duplicate of https://github.com/runescapejon/PokeTextures/issues/4
the other one has more information.

**Closed as completed by runescapejon** 2019-03-14 04:29 UTC
Labels: enhancement
